kind: Service
apiVersion: v1
metadata:
 name: gossiprouter-remoting
spec:
 ports:
 - port: 12001
   targetPort: 49773
---
kind: Endpoints
apiVersion: v1
metadata:
 name: gossiprouter-remoting
subsets:
 - addresses:
     - ip: 192.168.205.237
   ports:
     - port: 49773