kind: Service
apiVersion: v1
metadata:
 name: jms01
spec:
 clusterIP: None
 ports:
 - port: 5445
   targetPort: 5445
   name: portone
 - port: 4447
   targetPort: 4447
   name: porttwo
 - port: 9600
   targetPort: 9600
   name: portthree
---
kind: Endpoints
apiVersion: v1
metadata:
 name: jms01
subsets:
 - addresses:
     - ip: 192.168.205.237
   ports:
     - port: 5445
       name: portone
     - port: 4447
       name: porttwo
     - port: 9600
       name: portthree